### ISSUE TITLE
NumberGame.getCount() is incorrect

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/guessing-game-cynic4018#6]
Please check [document](https://skeoop.github.io/week1/Lab1-Guessing-Game.pdf) on Problem 6

https://github.com/OOP2018/guessing-game-cynic4018/blob/f4145c271c37a6a178c06333f407bd9690cf66f3/src/NumberGame.java#L59-L65

**Comment by cynic4018** [comment]
@chinnonae 
I change to 

public int getCount(){ 
 		return 0; 
 	} 

it's okay.Right?

**Comment by chinnonae** [comment]
Yes it is.
